name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      group: dev-runner-grp
      labels: [self-hosted, Linux, ARM64]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Read version from version.txt
      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      # Step 4: Replace placeholder in pom.xml
      - name: Update pom.xml version
        run: |
          sed -i "s|#{versionid}#|${{ env.VERSION }}|g" pom.xml
          echo "Updated pom.xml version to ${{ env.VERSION }}"

      # Step 5: Set environment variables
      - name: Set environment variables for tools
        run: |
          # Set JAVA_HOME explicitly to the JDK root
          echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

          # Capture other tool paths
          echo "MAVEN_PATH=$(which mvn)" >> $GITHUB_ENV
          echo "DOCKER_PATH=$(which docker)" >> $GITHUB_ENV
          echo "NODE_PATH=$(which node)" >> $GITHUB_ENV
          echo "NPM_PATH=$(which npm)" >> $GITHUB_ENV

          # Capture versions
          echo "JAVA_VERSION=$(java -version 2>&1 | head -n 1)" >> $GITHUB_ENV
          echo "MAVEN_VERSION=$(mvn -v | head -n 1)" >> $GITHUB_ENV
          echo "DOCKER_VERSION=$(docker --version)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV
          echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV

      # Step 6: Show tool info
      - name: Show tool info
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Java Version: $JAVA_VERSION"
          echo "Maven Path: $MAVEN_PATH"
          echo "Maven Version: $MAVEN_VERSION"
          echo "Docker Path: $DOCKER_PATH"
          echo "Docker Version: $DOCKER_VERSION"
          echo "Node Path: $NODE_PATH"
          echo "Node Version: $NODE_VERSION"
          echo "npm Path: $NPM_PATH"
          echo "npm Version: $NPM_VERSION"

      # Step 7: Build with Maven
      - name: Build with Maven
        run: mvn clean install -B

      # Step 8: Check build artifacts
      - name: Path Check
        run: |
          pwd
          ls -l target/

      # Step 9: Build the Docker image
      - name: Build the Docker image
        run: |
          echo "Building Docker image..."
          docker build -t hello-world-app:${{ env.VERSION }} .
