name: Hello Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: hello-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  say-hello:
    runs-on:
      group: dev-runner-grp
      labels: [self-hosted, Linux, X64]
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions 🎉"
