name: Hello Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: hello-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  say-hello:
    runs-on:
      group: dev-runner-grp
      labels: [self-hosted, Linux, ARM64]
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions 🎉"

      - name: Show Java path & version
        run: |
          which java || echo "Java not found"
          java -version || true

      - name: Show Maven path & version
        run: |
          which mvn || echo "Maven not found"
          mvn -v || true

      - name: Show Docker path & version
        run: |
          which docker || echo "Docker not found"
          docker --version || true

      - name: Show Node.js path & version
        run: |
          which node || echo "Node.js not found"
          node -v || true

      - name: Show npm path & version
        run: |
          which npm || echo "npm not found"
          npm -v || true
