name: Mixed Stress Test with Logs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  stress-mixed:
    runs-on:
      group: dev-runner-grp
      labels: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install stress-ng and procps
        run: sudo apt-get update && sudo apt-get install -y stress-ng procps

      - name: Run Mixed stress (CPU + Memory + I/O) for 20 minutes with usage logs
        run: |
          MEM_TOTAL=$(grep MemTotal /proc/meminfo | awk '{print $2}')
          MEM_MB=$((MEM_TOTAL / 1024))
          STRESS_MEM=$((MEM_MB * 50 / 100))
          echo "Starting Mixed stress for 20 minutes..."
          for i in {1..40}; do
            echo "=== CPU & Memory snapshot $(date) ==="
            top -b -n 1 | head -n 10
            free -m
            sleep 30 &
          done &
          stress-ng --cpu $(nproc) --vm 1 --vm-bytes ${STRESS_MEM}M --hdd $(nproc) --hdd-bytes 500M --timeout 1200s --metrics-brief
